apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstrap-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootstrap
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      containers:
      - name: bootstrap-container
        image: ravipal33/bootstrap:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
